#!/bin/sh
[ -L ${0} ] && SCRIPT_DIR=$(readlink ${0}) || SCRIPT_DIR=${0}
SCRIPT_DIR=$(dirname ${SCRIPT_DIR})

relocate_remappings()
{
  command_line=${1}

  for w in $command_line; do
    if $(echo "$w" | grep -q ':='); then
      ros_remaps="$ros_remaps $w"
    else
      gazebo_args="$gazebo_args $w"
    fi
  done

  echo "$gazebo_args$ros_remaps" | cut -c 1-
}

final="$@"

EXT=so
if [ $(uname) = "Darwin" ]; then
    EXT=dylib
fi

# add ros plugin if does not exist
if [ `expr "$final" : ".*libgazebo_ros_paths_plugin\.$EXT.*"` -eq 0 ]
then
    final="$final -g `catkin_find --first-only libgazebo_ros_paths_plugin.$EXT`"
fi

# add ros api plugin if it does not already exist in the passed in arguments
if [ `expr "$final" : ".*libgazebo_ros_api_plugin\.$EXT.*"` -eq 0 ]
then
    final="$final -g `catkin_find --first-only libgazebo_ros_api_plugin.$EXT`"
fi

# add scene plugin
if [ `expr "$final" : ".*libgazebo_scene_plugin\.$EXT.*"` -eq 0 ]
then
    final="$final -g `catkin_find --first-only libgazebo_scene_plugin.$EXT`"
fi

setup_path=$(pkg-config --variable=prefix gazebo)/share/gazebo/

# source setup.sh, but keep local modifications to GAZEBO_MASTER_URI and GAZEBO_MODEL_DATABASE_URI
desired_master_uri="$GAZEBO_MASTER_URI"
desired_model_database_uri="$GAZEBO_MODEL_DATABASE_URI"
. $setup_path/setup.sh
if [ "$desired_master_uri" = "" ]; then
	desired_master_uri="$GAZEBO_MASTER_URI"
fi
if [ "$desired_model_database_uri" = "" ]; then
	desired_model_database_uri="$GAZEBO_MODEL_DATABASE_URI"
fi

final=$(relocate_remappings "${final}")

# Combine the commands
GAZEBO_MASTER_URI="$desired_master_uri" GAZEBO_MODEL_DATABASE_URI="$desired_model_database_uri" gzclient $final
