#!/usr/bin/env python
import copy
import numpy as np
import rospy
from gazebo_msgs.srv import GetPhysicsProperties
from gazebo_msgs.srv import SetPhysicsProperties, SetPhysicsPropertiesRequest

class PhysicsPropertiesRandomizer:
    def __init__(self, gravity_ratio_range=[0.5, 3.0], gazebo_ns='/gazebo'):
        rospy.init_node("physics_properties_randomizer")
        self._gravity_ratio_range = gravity_ratio_range
        rospy.wait_for_service(gazebo_ns + '/get_physics_properties')
        get_phys_prop = rospy.ServiceProxy(gazebo_ns + '/get_physics_properties', GetPhysicsProperties)
        try:
	    res = get_phys_prop()
            if not res.success:
	        rospy.logwarn(res.status_message)
        except rospy.ServiceException, e:
            rospy.logerr("Service call failed: %s" % e)
        self._default_props = res
        self._set_phys_prop = rospy.ServiceProxy(gazebo_ns + '/set_physics_properties', SetPhysicsProperties)
    def timer_callback(self, event):
        req = SetPhysicsPropertiesRequest()
        r_gravity = np.random.uniform(*self._gravity_ratio_range)
        req.time_step = self._default_props.time_step
        req.max_update_rate = self._default_props.max_update_rate
        req.gravity = copy.deepcopy(self._default_props.gravity)
        req.gravity.z *= r_gravity
        req.ode_config = copy.deepcopy(self._default_props.ode_config)
        try:
            res = self._set_phys_prop(req)
            if not res.success:
                rospy.logwarn(res.status_message)
        except rospy.ServiceException, e:
            rospy.logerr("Service call failed: %s" % e)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='Physics properties randomizer')
    parser.add_argument('-d', '--duration', type=float, default=1.0, help='Timer duration.')
    args = parser.parse_args(rospy.myargv()[1:])
    randomizer = PhysicsPropertiesRandomizer()
    rospy.Timer(rospy.Duration(args.duration), randomizer.timer_callback)
    rospy.spin()
